/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedMessageIdRouteImport } from './routes/embed/$messageId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MessageUsernameIndexRouteImport } from './routes/message/$username/index'
import { Route as MessageUsernameInboxRouteImport } from './routes/message/$username/inbox'
import { Route as MessageUsernameSlugRouteImport } from './routes/message/$username/$slug'
import { Route as EmbedFormWallRouteImport } from './routes/embed/form/wall'
import { Route as EmbedFormMiniWallRouteImport } from './routes/embed/form/mini-wall'
import { Route as EmbedDisplayWallRouteImport } from './routes/embed/display/wall'
import { Route as EmbedDisplayMiniWallRouteImport } from './routes/embed/display/mini-wall'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedMessageIdRoute = EmbedMessageIdRouteImport.update({
  id: '/embed/$messageId',
  path: '/embed/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageUsernameIndexRoute = MessageUsernameIndexRouteImport.update({
  id: '/message/$username/',
  path: '/message/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageUsernameInboxRoute = MessageUsernameInboxRouteImport.update({
  id: '/message/$username/inbox',
  path: '/message/$username/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageUsernameSlugRoute = MessageUsernameSlugRouteImport.update({
  id: '/message/$username/$slug',
  path: '/message/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedFormWallRoute = EmbedFormWallRouteImport.update({
  id: '/embed/form/wall',
  path: '/embed/form/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedFormMiniWallRoute = EmbedFormMiniWallRouteImport.update({
  id: '/embed/form/mini-wall',
  path: '/embed/form/mini-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDisplayWallRoute = EmbedDisplayWallRouteImport.update({
  id: '/embed/display/wall',
  path: '/embed/display/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDisplayMiniWallRoute = EmbedDisplayMiniWallRouteImport.update({
  id: '/embed/display/mini-wall',
  path: '/embed/display/mini-wall',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/embed/$messageId': typeof EmbedMessageIdRoute
  '/embed/display/mini-wall': typeof EmbedDisplayMiniWallRoute
  '/embed/display/wall': typeof EmbedDisplayWallRoute
  '/embed/form/mini-wall': typeof EmbedFormMiniWallRoute
  '/embed/form/wall': typeof EmbedFormWallRoute
  '/message/$username/$slug': typeof MessageUsernameSlugRoute
  '/message/$username/inbox': typeof MessageUsernameInboxRoute
  '/message/$username/': typeof MessageUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/embed/$messageId': typeof EmbedMessageIdRoute
  '/embed/display/mini-wall': typeof EmbedDisplayMiniWallRoute
  '/embed/display/wall': typeof EmbedDisplayWallRoute
  '/embed/form/mini-wall': typeof EmbedFormMiniWallRoute
  '/embed/form/wall': typeof EmbedFormWallRoute
  '/message/$username/$slug': typeof MessageUsernameSlugRoute
  '/message/$username/inbox': typeof MessageUsernameInboxRoute
  '/message/$username': typeof MessageUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/embed/$messageId': typeof EmbedMessageIdRoute
  '/embed/display/mini-wall': typeof EmbedDisplayMiniWallRoute
  '/embed/display/wall': typeof EmbedDisplayWallRoute
  '/embed/form/mini-wall': typeof EmbedFormMiniWallRoute
  '/embed/form/wall': typeof EmbedFormWallRoute
  '/message/$username/$slug': typeof MessageUsernameSlugRoute
  '/message/$username/inbox': typeof MessageUsernameInboxRoute
  '/message/$username/': typeof MessageUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/profile'
    | '/setup'
    | '/sso-callback'
    | '/auth/callback'
    | '/embed/$messageId'
    | '/embed/display/mini-wall'
    | '/embed/display/wall'
    | '/embed/form/mini-wall'
    | '/embed/form/wall'
    | '/message/$username/$slug'
    | '/message/$username/inbox'
    | '/message/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/profile'
    | '/setup'
    | '/sso-callback'
    | '/auth/callback'
    | '/embed/$messageId'
    | '/embed/display/mini-wall'
    | '/embed/display/wall'
    | '/embed/form/mini-wall'
    | '/embed/form/wall'
    | '/message/$username/$slug'
    | '/message/$username/inbox'
    | '/message/$username'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/profile'
    | '/setup'
    | '/sso-callback'
    | '/auth/callback'
    | '/embed/$messageId'
    | '/embed/display/mini-wall'
    | '/embed/display/wall'
    | '/embed/form/mini-wall'
    | '/embed/form/wall'
    | '/message/$username/$slug'
    | '/message/$username/inbox'
    | '/message/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SetupRoute: typeof SetupRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmbedMessageIdRoute: typeof EmbedMessageIdRoute
  EmbedDisplayMiniWallRoute: typeof EmbedDisplayMiniWallRoute
  EmbedDisplayWallRoute: typeof EmbedDisplayWallRoute
  EmbedFormMiniWallRoute: typeof EmbedFormMiniWallRoute
  EmbedFormWallRoute: typeof EmbedFormWallRoute
  MessageUsernameSlugRoute: typeof MessageUsernameSlugRoute
  MessageUsernameInboxRoute: typeof MessageUsernameInboxRoute
  MessageUsernameIndexRoute: typeof MessageUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$messageId': {
      id: '/embed/$messageId'
      path: '/embed/$messageId'
      fullPath: '/embed/$messageId'
      preLoaderRoute: typeof EmbedMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/$username/': {
      id: '/message/$username/'
      path: '/message/$username'
      fullPath: '/message/$username/'
      preLoaderRoute: typeof MessageUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/$username/inbox': {
      id: '/message/$username/inbox'
      path: '/message/$username/inbox'
      fullPath: '/message/$username/inbox'
      preLoaderRoute: typeof MessageUsernameInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/$username/$slug': {
      id: '/message/$username/$slug'
      path: '/message/$username/$slug'
      fullPath: '/message/$username/$slug'
      preLoaderRoute: typeof MessageUsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/form/wall': {
      id: '/embed/form/wall'
      path: '/embed/form/wall'
      fullPath: '/embed/form/wall'
      preLoaderRoute: typeof EmbedFormWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/form/mini-wall': {
      id: '/embed/form/mini-wall'
      path: '/embed/form/mini-wall'
      fullPath: '/embed/form/mini-wall'
      preLoaderRoute: typeof EmbedFormMiniWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/display/wall': {
      id: '/embed/display/wall'
      path: '/embed/display/wall'
      fullPath: '/embed/display/wall'
      preLoaderRoute: typeof EmbedDisplayWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/display/mini-wall': {
      id: '/embed/display/mini-wall'
      path: '/embed/display/mini-wall'
      fullPath: '/embed/display/mini-wall'
      preLoaderRoute: typeof EmbedDisplayMiniWallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SetupRoute: SetupRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmbedMessageIdRoute: EmbedMessageIdRoute,
  EmbedDisplayMiniWallRoute: EmbedDisplayMiniWallRoute,
  EmbedDisplayWallRoute: EmbedDisplayWallRoute,
  EmbedFormMiniWallRoute: EmbedFormMiniWallRoute,
  EmbedFormWallRoute: EmbedFormWallRoute,
  MessageUsernameSlugRoute: MessageUsernameSlugRoute,
  MessageUsernameInboxRoute: MessageUsernameInboxRoute,
  MessageUsernameIndexRoute: MessageUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
